# -*- coding: utf-8 -*-
"""EGEA_suspension_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xj3RYB1MkztmRlC_bxhCGfORLb9HFm4J

# Implementacja numeryczna badania tłumienia zawieszenia pojazdu
## Model Ćwiartkowy (Quarter Car Model) zgodnie ze standardem EGEA

Celem tego notatnika jest przeprowadzenie symulacji komputerowej badania sprawności amortyzatorów. Zaimplementowano model 2DOF (ćwiartkowy model zawieszenia) oraz procedurę wymuszeń kinematycznych zgodną ze standardem EGEA, uwzględniającą cykliczność działania płyt wymuszających.

### 1. Model Fizyczny i Matematyczny oraz Parametry
Układ równań różniczkowych drugiego rzędu został przekształcony do postaci wektorowej pierwszego rzędu: $\dot{X}(t) = A \cdot X(t) + B(t)$,
gdzie wektor stanu to $X = [x_m, x_M, v_m, v_M]^T$.
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# Ustawienia wykresów
plt.rcParams['figure.figsize'] = (12, 10)
plt.rcParams['font.size'] = 12

# 1 i 2. Parametry Symulacji (sprawny amortyzator przedni)
M = 346.0      # Masa resorowana [kg]
m = 36.0       # Masa nieresorowana [kg]
kM = 25570.0   # Sztywność zawieszenia [N/m]
km = 253161.0  # Sztywność opony [N/m]
cM = 1474.0    # Tłumienie amortyzatora [N*s/m]
cm = 150.0     # Tłumienie opony [N*s/m]

d = 0.003      # Amplituda wymuszenia [m] (skok 6 mm)
g = 9.81       # Przyspieszenie ziemskie [m/s^2]

# Siła statyczna nacisku (masa całkowita * g)
F_st = (M + m) * g

# Parametry całkowania i próbkowania
fs = 10000.0   # Częstotliwość próbkowania: 10 kHz
dt = 1.0 / fs  # Krok czasu: 1e-4 s

"""### 3. Funkcja Zmienności Częstotliwości
Zgodnie z wymaganiami wyznaczamy funkcję, która modeluje:
- **Faza 1 (Rozruch)**: Liniowy wzrost 0 – 25 Hz.
- **Faza 2 (Stabilizacja)**: Stałe 25 Hz przez czas $\Delta T_{25}$.
- **Faza 3 (Rampa pomiarowa)**: Liniowy spadek od 18 Hz do 6 Hz w minimum 7.5 s.
- **Faza 4 (Wygaszenie)**: Spadek do 0 Hz.
"""

# Wyliczenie czasu trwania fazy 2
dT25_ms = F_st * 0.16 + 1200.0  # w ms
dT25 = dT25_ms / 1000.0         # w sekundach

# Całkowity czas symulacji (oszacowany na podstawie faz EGEA)
T_total = 14.5 + dT25
t = np.arange(0, T_total, dt)

print(f"Siła statyczna F_st: {F_st:.2f} N")
print(f"Czas trwania stabilizacji 25 Hz: {dT25:.2f} s")

# Funkcja wyznaczająca obwiednię częstotliwości
def get_target_frequency(t_val):
    T1 = 2.0  # Czas rozruchu 0-25 Hz [s]
    T2_end = T1 + dT25  # Koniec stabilizacji 25 Hz (ok. 6.8 s)
    T_prep = 2.0  # Spadek przygotowujący 25 -> 18 Hz
    T3_start = T2_end + T_prep
    T_meas = 7.5  # Właściwa rampa pomiarowa 18 -> 6 Hz
    T3_end = T3_start + T_meas
    T_ext = 3.0   # Wygaszenie 6 -> 0 Hz
    T4_end = T3_end + T_ext

    if t_val < T1:
        return 2.0 + (23.0 / T1) * t_val
    elif t_val < T2_end:
        return 25.0
    elif t_val < T3_start:
        return 25.0 - ((t_val - T2_end) / T_prep) * (25.0 - 18.0)
    elif t_val < T3_end:
        return 18.0 - ((t_val - T3_start) / T_meas) * (18.0 - 6.0)
    elif t_val < T4_end:
        return 6.0 - ((t_val - T3_end) / T_ext) * (6.0 - 0.0)
    else:
        return 0.0

"""### 4. Logika „Nieidealnej” Częstotliwości (Cykliczność)
Płyta wzbudnika kończy pełny cykl drgania w zdefiniowanych momentach czasu $t_k$. Częstotliwość $f$ jest obliczana dla każdego cyklu i pozostaje stała przez cały cykl trwający $1/f$.
"""

# Dodana funkcja omega(t) - zwraca docelową (ciągłą) częstość kątową w rad/s
def omega_func(t_val):
    """Calculates the target angular frequency in rad/s based on the time."""
    return 2 * np.pi * get_target_frequency(t_val)

# Nowa logika wyznaczania punktów czasu t_k i częstotliwości f_k,
# tak aby t_next było pochodną t_current i funkcji omega.
t_k = [0.0]
f_k = []

current_t = 0.0
while current_t < T_total:
    target_f_at_current_t = get_target_frequency(current_t)
    if target_f_at_current_t > 0:
        # Czas trwania cyklu wynosi 1/f
        period = 1.0 / target_f_at_current_t
        t_next = current_t + period
        if t_next > T_total:
            t_next = T_total # Nie wykraczamy poza całkowity czas symulacji
            period = t_next - current_t # Dostosuj okres dla ostatniego fragmentu
            if period <= 0 and current_t < T_total: # Avoid division by zero if period becomes 0 at T_total
                break
            if period > 0:
                f_k.append(1.0 / period)
            else:
                f_k.append(0.0) # Frequency is 0 if no time passed
            t_k.append(t_next)
            break # Koniec symulacji

        f_k.append(target_f_at_current_t)
        t_k.append(t_next)
        current_t = t_next
    else:
        # Jeżeli częstotliwość docelowa wynosi 0, po prostu przesuń czas do końca symulacji
        # lub do następnego znaczącego momentu (np. 1 krok dt, aby uniknąć nieskończonej pętli)
        if current_t < T_total:
            # Dodaj 0Hz segment do końca lub do momentu zmiany częstotliwości
            if len(f_k) == 0 or f_k[-1] != 0:
                f_k.append(0.0)
                t_k.append(current_t + dt) # Small step to ensure progress
            current_t += dt
        else:
            break

# Upewnij się, że t_k i f_k są numpy array
t_k = np.array(t_k)
f_k = np.array(f_k)

# Przygotowanie wektorów ruchu płyty z(t), prędkości z_dot(t) oraz częstotliwości skokowej f_step(t)
z = np.zeros_like(t)
z_dot = np.zeros_like(t)
f_step = np.zeros_like(t)

current_k = 0
for i, t_i in enumerate(t):
    # Znajdź odpowiedni cykl k dla chwili czasu t_i
    # Advance current_k to the correct interval for t_i
    while current_k < len(t_k) - 1 and t_i >= t_k[current_k + 1]:
        current_k += 1

    # Now, after potentially advancing current_k, check if we are at the last interval
    if current_k >= len(t_k) - 1:
        # If t_i is beyond the last defined interval in t_k,
        # use the last frequency or 0, and maintain previous position/velocity.
        # This handles the end condition correctly.
        if len(f_k) > 0:
            f_step[i] = f_k[-1]
        else:
            f_step[i] = 0.0
        z[i] = z[i-1] if i > 0 else d # Maintain last position
        z_dot[i] = 0.0 # Or based on last cycle's end velocity if needed, but 0 is safe
        continue # Move to the next t_i

    # If we are here, current_k is a valid index such that current_k + 1 is also valid
    t_current = t_k[current_k]
    t_next = t_k[current_k + 1]

    # Obliczenie fazy drgań i jej pochodnej
    # theta_dot jest teraz bezpośrednio związana z f_k[current_k]
    if (t_next - t_current) > 0: # Avoid division by zero
        theta = 2 * np.pi * (t_i - t_current) / (t_next - t_current)
        theta_dot = 2 * np.pi / (t_next - t_current)
    else:
        theta = 0.0
        theta_dot = 0.0

    # Równania ruchu i prędkości płyty wymuszającej
    z[i] = -d * np.cos(theta)
    z_dot[i] = d * np.sin(theta) * theta_dot
    f_step[i] = f_k[current_k]

# Definicja t_fine (bardziej 'ciągły' zakres czasu do wykresu)
dt_fine = 0.001 # Większy krok czasu dla 'ciągłego' wykresu
t_fine = np.arange(0, T_total, dt_fine)

# Obliczenie f_fine (ciągły profil częstotliwości docelowej)
f_fine = np.array([get_target_frequency(t_val) for t_val in t_fine])

"""### 5. Obliczenia i Integracja Numeryczna
Używamy narzędzia `odeint` ze zdefiniowanym wektorem wymuszenia wektorowego $B(t)$.
"""

# Macierz A opisująca zależności pomiędzy stanami: [x_m, x_M, v_m, v_M]
A = np.array([
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [-(km + kM)/m, kM/m, -(cm + cM)/m, cM/m],
    [kM/M, -kM/M, cM/M, -cM/M]
])

def model(X, t_val):
    # Odeint może pytać o wartości t w dowolnym momencie (niekoniecznie krok dt).
    # Dlatego mapujemy dany czas na najbliższy indeks w prekomputowanych tablicach z(t) i z_dot(t).
    idx = int(t_val / dt)
    if idx >= len(z):
        idx = len(z) - 1

    z_val = z[idx]
    z_dot_val = z_dot[idx]

    # Wektor pobudzenia B(t)
    B = np.array([0, 0, (km * z_val + cm * z_dot_val) / m, 0])

    return np.dot(A, X) + B

# Warunki początkowe X0 = [x_m(0), x_M(0), v_m(0), v_M(0)]
# Ustawiamy początkowe ugięcie statyczne jako d (zgodnie ze wzniesieniem płyty t=0, z(0)=d)
X0 = [0, 0, 0, 0]

print("Rozpoczynam całkowanie numeryczne. Może to potrwać kilkanaście sekund...")
X_sol = odeint(model, X0, t)
print("Zakończono całkowanie.")

x_m = X_sol[:, 0]  # Odchylenie masy nieresorowanej
v_m = X_sol[:, 2]  # Prędkość masy nieresorowanej

# ------------------------------------------------------------
# Obliczanie dynamicznej i całkowitej siły nacisku opony na płytę
# F(t) = F_st + c_m * (v_m - z_dot) + k_m * (x_m - z)
# ------------------------------------------------------------
F_dyn = km * (x_m - z) + cm * (v_m - z_dot)
F_t = F_st + F_dyn

# Wskaźnik EUSAMA - najniższa wartość z zakresu pomiarowego (rampy opadającej 18 do 6 Hz)
idx_measure = np.where((f_step <= 18) & (f_step >= 6))[0]
if len(idx_measure) > 0:
    F_min = np.min(F_t[idx_measure])
    eusama = (F_min / F_st) * 100
    print(f"\nWynik badania - Wskaźnik EUSAMA: {eusama:.2f}%")
else:
    print("\nBrak danych w zakresie częstotliwości pomiarowej.")

"""### 6. Wizualizacja Wyników
Prezentacja czterech głównych przebiegów wyznaczonych z symulacji.
"""

fig, axs = plt.subplots(4, 1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.3)

# Wykres 1: Profil częstotliwości pokazujący "schodki" modelowane cyklami
axs[0].plot(t, f_step, color='purple')
axs[0].set_title('Profil częstotliwości wzbudnika', fontweight='bold')
axs[0].set_ylabel('Częstotliwość [Hz]')
axs[0].grid(True)

# Wykres 2: Ruch płyty z(t)
axs[1].plot(t, z, color='blue')
axs[1].set_title('Ruch płyty wymuszającej z(t)', fontweight='bold')
axs[1].set_ylabel('Przemieszczenie z [m]')
axs[1].grid(True)

# Wykres 3: Odchylenie masy nieresorowanej x_m(t)
axs[2].plot(t, x_m, color='green')
axs[2].set_title('Trajektoria ruchu masy nieresorowanej (koła) x_m(t)', fontweight='bold')
axs[2].set_ylabel('Odchylenie x_m [m]')
axs[2].grid(True)

# Wykres 4: Siła nacisku F(t)
axs[3].plot(t, F_t, color='orange', label='F_t (Siła dynamiczna całkowita)')
axs[3].axhline(F_st, color='red', linestyle='--', linewidth=2, label='F_st (Siła statyczna)')
axs[3].fill_between(t, 0, F_t, where=(f_step <= 18) & (f_step >= 6), color='gray', alpha=0.3, label='Faza pomiaru EUSAMA')
axs[3].set_title('Dynamiczna siła kontaktu opony z podłożem F(t)', fontweight='bold')
axs[3].set_xlabel('Czas [s]')
axs[3].set_ylabel('Siła nacisku F [N]')
axs[3].legend(loc='upper right')
axs[3].grid(True)

plt.show()

fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(t_fine, f_fine, color='blue', label='Ciągły profil docelowy')
ax.plot(t, f_step, color='red', linestyle='--', label='Cykliczne przybliżenie (f_step)')
ax.set_title('Porównanie ciągłego i cyklicznego profilu częstotliwości', fontweight='bold')
ax.set_xlabel('Czas [s]')
ax.set_ylabel('Częstotliwość [Hz]')
ax.grid(True)
ax.legend()

plt.show()

"""---
# Projekt **MinPhraseShift**

(1) Symulacja $F(t), \quad z(t)=\ldots \text{wzór} \ldots$

(2) Symulacja $S, ST_i$

(3) Macierz kalibrcji $\Delta_{\text{Perid}}(i)$

>  (a) Procedura tworzenia

>  (b) Procedura używania → $TOP_p(i)$

(4) $F_p(t)$ - na podstawie $TOP_p(i)$

(5) $X_{Fup}, X_{Fdn} → F_{ref}(i)$

(6) Wyznaczenie minimalnego przesunięcia fazowego

---
* Wczytujemy tablicę czasów `t = [0.0, 0.001, ...]`
* `F[...]`
* `S=[0,0,...,1,1,0,...] ← czujnik widzi płytę`

Ramka = $[(t_0, F_0, S_0), (t_1,F_1,S_1), \ldots, (t_n, F_n, S_n)]$

---
**Uwagi:**
* Jako $ST_i$ bierzemy pierwszą 1 z S.
* Będziemy działać na jednym `np.linspace`

---
$$\ddot{x}+2\theta\omega_0\dot{x}+\omega_0^2x=f(t), \quad f(t)=A\cos\omega t + B\sin \omega t$$
$$x(0)=x_0, \dot{x}(0)=v_0$$

---
```
m = 382 kg

c = 1474 (zmienniać się będzie)

z(t)=-d*cos(omega t)

d = 0.003
```
---

**Zadanie:** Znaleść zależność pomiędzy minimalnym przesunięciem fazowym w modelu 1DOF dla częstotliwości 18 Hz do 6 Hz i tłumienia.
Według metody z normy według krzywej częstotliwości.
Stworzyć wykresy: $\phi(\omega)$ i zmianą częstotliwości w [Hz] oraz  dla kilku $c$ wykresy $\phi_{min}$ i $c$.

---
Użytkownik podaje plik CSV w którym są 3 kolumny: `t, F, S` na ich podstawie program wyznacza minimalne przesunięcei fazowe. W drugim etapie zmieniamy `c` i otzymujemy inne symulacje i patrzymy jaki jest związewk między minimalnym przesunięciem fazowym a tłumienim.

---
Musimu wiąć korektę na płytę ale nie mamy szumów.
"""

